name: GithubApiTask

options:
  bundleIdPrefix: com.kazua
  deploymentTarget:
    iOS: 13.0
  developmentLanguage: ja

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    version: 5.4.0

targets:
  GithubApiTask:
    type: application
    platform: iOS
    sources:
      - GithubApiTask
    settings:
      base:
        INFOPLIST_FILE: GithubApiTask/Application/Info.plist
        DEVELOPMENT_LANGUAGE: jp
    dependencies:
      - package: Alamofire
    postCompileScripts:
      - path: ./Scripts/XcodeGen/swiftlint.sh
        name: Run SwiftLint

schemes:
  GithubApiTask:
    build:
      targets:
        GithubApiTask: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
